import type { Requisition } from "@/types/RequisitionType"

export const testdata1: Requisition[] = [
  {
    id: "XX111",
    parentId: "XX11",
    sequence: 1,
    query: "Are there any contents included?",
    isApplicable: false,
    hasDoc: false,
    isComplete: false,
    isFlagged: false,
  },
  {
    id: "XX11",
    parentId: "XX1",
    sequence: 1,
    query: "",
    isApplicable: false,
    hasDoc: false,
    isComplete: false,
    isFlagged: false,
  },
  {
    id: "XX2",
    parentId: "",
    sequence: 2,
    query: "Water Services/Local Authority",
    isApplicable: false,
    hasDoc: false,
    isComplete: false,
    isFlagged: false,
  },
  {
    id: "XX21",
    parentId: "XX2",
    sequence: 1,
    query: "Is the property serviced with:",
    isApplicable: false,
    hasDoc: false,
    isComplete: false,
    isFlagged: false,
  },
  {
    id: "XX211",
    parentId: "XX21",
    sequence: 1,
    query: "Sewerage",
    isApplicable: false,
    hasDoc: false,
    isComplete: false,
    isFlagged: false,
  },
  {
    id: "XX2111",
    parentId: "XX211",
    sequence: 1,
    query:
      "if so, state whether by Irish Water mains, on-site domestic septic tank or other on-site domestic waste water treatment system, or other",
    isApplicable: true,
    hasDoc: false,
    isComplete: false,
    isFlagged: false,
  },
  {
    id: "XX2112",
    parentId: "XX211",
    sequence: 2,
    query:
      "if by Irish Water mains, furnish evidence of registration with Irish Water",
    isApplicable: true,
    hasDoc: false,
    isComplete: false,
    isFlagged: false,
  },
  {
    id: "XX2113",
    parentId: "XX211",
    sequence: 3,
    query:
      "if by on-site domestic septic tank or other on-site domestic waste water treatment system, furnish evidence of registration of the system with Protect Our Water",
    isApplicable: true,
    hasDoc: false,
    isComplete: false,
    isFlagged: false,
  },
  {
    id: "XX112",
    parentId: "XX11",
    sequence: 2,
    query:
      "If so, furnish a list of same and give the Vendor's estimate of value",
    isApplicable: true,
    hasDoc: false,
    isComplete: false,
    isFlagged: false,
  },
  {
    id: "XX1",
    parentId: "",
    sequence: 1,
    query: "Premises",
    isApplicable: true,
    hasDoc: false,
    isComplete: false,
    isFlagged: false,
  },
  {
    id: "XX3",
    parentId: "",
    sequence: 3,
    query: "Easements and Rights",
    isApplicable: true,
    hasDoc: false,
    isComplete: false,
    isFlagged: false,
  },
  {
    id: "XX31",
    parentId: "XX3",
    sequence: 1,
    query: "",
    isApplicable: true,
    hasDoc: false,
    isComplete: false,
    isFlagged: false,
  },
  {
    id: "XX311",
    parentId: "XX31",
    sequence: 1,
    query:
      "Are there any pipes drains sewers wires cables or septic tank on under or over other property which serve the property in sale",
    isApplicable: true,
    hasDoc: false,
    isComplete: false,
    isFlagged: false,
  },
]
