export const data = [
  {
    id: 18,
    parent_id: null,
    sequence: 1,
    query: "Premises",
    reply: null,
    is_applicable: true,
    has_doc: true,
    is_complete: true,
    is_flagged: true,
    is_required: true,
    status: null,
    children: [
      {
        id: 28,
        parent_id: 18,
        sequence: 1,
        query: "something about services",
        reply: null,
        is_applicable: false,
        has_doc: false,
        is_complete: false,
        is_flagged: false,
        is_required: false,
        status: null,
        children: [
          {
            id: 31,
            parent_id: 28,
            sequence: 2,
            query: "",
            reply: null,
            is_applicable: false,
            has_doc: false,
            is_complete: false,
            is_flagged: false,
            is_required: false,
            status: null,
            children: [],
            siblings: [3, 2],
            level: 3,
            sequence_in_levels: [1, 1, 2],
          },
          {
            id: 30,
            parent_id: 28,
            sequence: 3,
            query: "and about water",
            reply: null,
            is_applicable: false,
            has_doc: false,
            is_complete: false,
            is_flagged: false,
            is_required: true,
            status: null,
            children: [],
            siblings: [3, 2],
            level: 3,
            sequence_in_levels: [1, 1, 3],
          },
        ],
        siblings: [4, 3, 2, 1],
        level: 2,
        sequence_in_levels: [1, 1],
      },
      {
        id: 20,
        parent_id: 18,
        sequence: 2,
        query:
          "If so, furnish a list of same and give the Vendor’s estimate of value, and what it should be. This is something which needs to be discussed further.",
        reply: null,
        is_applicable: true,
        has_doc: false,
        is_complete: false,
        is_flagged: false,
        is_required: false,
        status: null,
        children: [
          {
            id: 29,
            parent_id: 20,
            sequence: 1,
            query: "a mini query",
            reply: null,
            is_applicable: false,
            has_doc: false,
            is_complete: false,
            is_flagged: false,
            is_required: true,
            status: null,
            children: [],
            siblings: [2, 1],
            level: 3,
            sequence_in_levels: [1, 2, 1],
          },
          {
            id: 26,
            parent_id: 20,
            sequence: 2,
            query: "something related to contents",
            reply: null,
            is_applicable: false,
            has_doc: false,
            is_complete: false,
            is_flagged: false,
            is_required: true,
            status: null,
            children: [],
            siblings: [2, 1],
            level: 3,
            sequence_in_levels: [1, 2, 2],
          },
        ],
        siblings: [4, 3, 2, 1],
        level: 2,
        sequence_in_levels: [1, 2],
      },
      {
        id: 19,
        parent_id: 18,
        sequence: 3,
        query: "Are there any contents?",
        reply: null,
        is_applicable: true,
        has_doc: true,
        is_complete: true,
        is_flagged: true,
        is_required: true,
        status: null,
        children: [
          {
            id: 24,
            parent_id: 19,
            sequence: 1,
            query: "",
            reply: null,
            is_applicable: false,
            has_doc: false,
            is_complete: false,
            is_flagged: false,
            is_required: true,
            status: null,
            children: [
              {
                id: 25,
                parent_id: 24,
                sequence: 1,
                query:
                  "The list of famous English sporting defeats has a new entry. Congratulations to the great rugby nation of Fiji for rewriting Pacific Island oval ball history but never before has English rugby taken such a massive reputational dive. To say Steve Borthwick’s team have a few problems to solve before the Rugby World Cup kicks off next month is the understatement of the decade.\n\nShort of winning Olympic Sevens gold for the first time in Rio in 2016 it is difficult to imagine a result that will generate more pride and joy in the streets of Suva and Lautoka and every rugby-mad village in between. Equally, the frustrated gnashing of teeth in Middle England is now deafening. Twenty-five thousand empty seats at Twickenham is no accident and neither was this outcome.",
                reply: null,
                is_applicable: false,
                has_doc: false,
                is_complete: false,
                is_flagged: false,
                is_required: true,
                status: null,
                children: [
                  {
                    id: 27,
                    parent_id: 25,
                    sequence: 2,
                    query:
                      "When he decided on a career switch into politics, he wasn’t required, as many wannabe parliamentarians are, to demonstrate his commitment by first fighting an unwinnable constituency. He bagged a safe Conservative seat at the first time of asking. He was an MP at the age of 34 and chancellor before he turned 40. And then the wheel of fortune turned against him. He was promoted to Number 10 at the worst point of the political cycle to become prime minister.",
                    reply: null,
                    is_applicable: false,
                    has_doc: false,
                    is_complete: false,
                    is_flagged: false,
                    is_required: false,
                    status: null,
                    children: [],
                    siblings: [2],
                    level: 5,
                    sequence_in_levels: [1, 3, 1, 1, 2],
                  },
                ],
                siblings: [1],
                level: 4,
                sequence_in_levels: [1, 3, 1, 1],
              },
            ],
            siblings: [1, 2],
            level: 3,
            sequence_in_levels: [1, 3, 1],
          },
          {
            id: 23,
            parent_id: 19,
            sequence: 2,
            query: "there must be some contents",
            reply: null,
            is_applicable: false,
            has_doc: false,
            is_complete: false,
            is_flagged: false,
            is_required: false,
            status: null,
            children: [],
            siblings: [1, 2],
            level: 3,
            sequence_in_levels: [1, 3, 2],
          },
        ],
        siblings: [4, 3, 2, 1],
        level: 2,
        sequence_in_levels: [1, 3],
      },
      {
        id: 21,
        parent_id: 18,
        sequence: 4,
        query:
          "Furnish a copy of a valid Building Energy Rating certificate and related advisory report in respect of the property.",
        reply: null,
        is_applicable: true,
        has_doc: true,
        is_complete: true,
        is_flagged: true,
        is_required: true,
        status: null,
        children: [],
        siblings: [4, 3, 2, 1],
        level: 2,
        sequence_in_levels: [1, 4],
      },
    ],
    siblings: [1],
    level: 1,
    sequence_in_levels: [1],
  },
  {
    id: 28,
    parent_id: 18,
    sequence: 1,
    query: "something about services",
    reply: null,
    is_applicable: false,
    has_doc: false,
    is_complete: false,
    is_flagged: false,
    is_required: false,
    status: null,
    children: [
      {
        id: 31,
        parent_id: 28,
        sequence: 2,
        query: "",
        reply: null,
        is_applicable: false,
        has_doc: false,
        is_complete: false,
        is_flagged: false,
        is_required: false,
        status: null,
        children: [],
        siblings: [3, 2],
        level: 3,
        sequence_in_levels: [1, 1, 2],
      },
      {
        id: 30,
        parent_id: 28,
        sequence: 3,
        query: "and about water",
        reply: null,
        is_applicable: false,
        has_doc: false,
        is_complete: false,
        is_flagged: false,
        is_required: true,
        status: null,
        children: [],
        siblings: [3, 2],
        level: 3,
        sequence_in_levels: [1, 1, 3],
      },
    ],
    siblings: [4, 3, 2, 1],
    level: 2,
    sequence_in_levels: [1, 1],
  },
  {
    id: 31,
    parent_id: 28,
    sequence: 2,
    query: "",
    reply: null,
    is_applicable: false,
    has_doc: false,
    is_complete: false,
    is_flagged: false,
    is_required: false,
    status: null,
    children: [],
    siblings: [3, 2],
    level: 3,
    sequence_in_levels: [1, 1, 2],
  },
  {
    id: 30,
    parent_id: 28,
    sequence: 3,
    query: "and about water",
    reply: null,
    is_applicable: false,
    has_doc: false,
    is_complete: false,
    is_flagged: false,
    is_required: true,
    status: null,
    children: [],
    siblings: [3, 2],
    level: 3,
    sequence_in_levels: [1, 1, 3],
  },
  {
    id: 20,
    parent_id: 18,
    sequence: 2,
    query:
      "If so, furnish a list of same and give the Vendor’s estimate of value, and what it should be. This is something which needs to be discussed further.",
    reply: null,
    is_applicable: true,
    has_doc: false,
    is_complete: false,
    is_flagged: false,
    is_required: false,
    status: null,
    children: [
      {
        id: 29,
        parent_id: 20,
        sequence: 1,
        query: "a mini query",
        reply: null,
        is_applicable: false,
        has_doc: false,
        is_complete: false,
        is_flagged: false,
        is_required: true,
        status: null,
        children: [],
        siblings: [2, 1],
        level: 3,
        sequence_in_levels: [1, 2, 1],
      },
      {
        id: 26,
        parent_id: 20,
        sequence: 2,
        query: "something related to contents",
        reply: null,
        is_applicable: false,
        has_doc: false,
        is_complete: false,
        is_flagged: false,
        is_required: true,
        status: null,
        children: [],
        siblings: [2, 1],
        level: 3,
        sequence_in_levels: [1, 2, 2],
      },
    ],
    siblings: [4, 3, 2, 1],
    level: 2,
    sequence_in_levels: [1, 2],
  },
  {
    id: 29,
    parent_id: 20,
    sequence: 1,
    query: "a mini query",
    reply: null,
    is_applicable: false,
    has_doc: false,
    is_complete: false,
    is_flagged: false,
    is_required: true,
    status: null,
    children: [],
    siblings: [2, 1],
    level: 3,
    sequence_in_levels: [1, 2, 1],
  },
  {
    id: 26,
    parent_id: 20,
    sequence: 2,
    query: "something related to contents",
    reply: null,
    is_applicable: false,
    has_doc: false,
    is_complete: false,
    is_flagged: false,
    is_required: true,
    status: null,
    children: [],
    siblings: [2, 1],
    level: 3,
    sequence_in_levels: [1, 2, 2],
  },
  {
    id: 19,
    parent_id: 18,
    sequence: 3,
    query: "Are there any contents?",
    reply: null,
    is_applicable: true,
    has_doc: true,
    is_complete: true,
    is_flagged: true,
    is_required: true,
    status: null,
    children: [
      {
        id: 24,
        parent_id: 19,
        sequence: 1,
        query: "",
        reply: null,
        is_applicable: false,
        has_doc: false,
        is_complete: false,
        is_flagged: false,
        is_required: true,
        status: null,
        children: [
          {
            id: 25,
            parent_id: 24,
            sequence: 1,
            query:
              "The list of famous English sporting defeats has a new entry. Congratulations to the great rugby nation of Fiji for rewriting Pacific Island oval ball history but never before has English rugby taken such a massive reputational dive. To say Steve Borthwick’s team have a few problems to solve before the Rugby World Cup kicks off next month is the understatement of the decade.\n\nShort of winning Olympic Sevens gold for the first time in Rio in 2016 it is difficult to imagine a result that will generate more pride and joy in the streets of Suva and Lautoka and every rugby-mad village in between. Equally, the frustrated gnashing of teeth in Middle England is now deafening. Twenty-five thousand empty seats at Twickenham is no accident and neither was this outcome.",
            reply: null,
            is_applicable: false,
            has_doc: false,
            is_complete: false,
            is_flagged: false,
            is_required: true,
            status: null,
            children: [
              {
                id: 27,
                parent_id: 25,
                sequence: 2,
                query:
                  "When he decided on a career switch into politics, he wasn’t required, as many wannabe parliamentarians are, to demonstrate his commitment by first fighting an unwinnable constituency. He bagged a safe Conservative seat at the first time of asking. He was an MP at the age of 34 and chancellor before he turned 40. And then the wheel of fortune turned against him. He was promoted to Number 10 at the worst point of the political cycle to become prime minister.",
                reply: null,
                is_applicable: false,
                has_doc: false,
                is_complete: false,
                is_flagged: false,
                is_required: false,
                status: null,
                children: [],
                siblings: [2],
                level: 5,
                sequence_in_levels: [1, 3, 1, 1, 2],
              },
            ],
            siblings: [1],
            level: 4,
            sequence_in_levels: [1, 3, 1, 1],
          },
        ],
        siblings: [1, 2],
        level: 3,
        sequence_in_levels: [1, 3, 1],
      },
      {
        id: 23,
        parent_id: 19,
        sequence: 2,
        query: "there must be some contents",
        reply: null,
        is_applicable: false,
        has_doc: false,
        is_complete: false,
        is_flagged: false,
        is_required: false,
        status: null,
        children: [],
        siblings: [1, 2],
        level: 3,
        sequence_in_levels: [1, 3, 2],
      },
    ],
    siblings: [4, 3, 2, 1],
    level: 2,
    sequence_in_levels: [1, 3],
  },
  {
    id: 24,
    parent_id: 19,
    sequence: 1,
    query: "",
    reply: null,
    is_applicable: false,
    has_doc: false,
    is_complete: false,
    is_flagged: false,
    is_required: true,
    status: null,
    children: [
      {
        id: 25,
        parent_id: 24,
        sequence: 1,
        query:
          "The list of famous English sporting defeats has a new entry. Congratulations to the great rugby nation of Fiji for rewriting Pacific Island oval ball history but never before has English rugby taken such a massive reputational dive. To say Steve Borthwick’s team have a few problems to solve before the Rugby World Cup kicks off next month is the understatement of the decade.\n\nShort of winning Olympic Sevens gold for the first time in Rio in 2016 it is difficult to imagine a result that will generate more pride and joy in the streets of Suva and Lautoka and every rugby-mad village in between. Equally, the frustrated gnashing of teeth in Middle England is now deafening. Twenty-five thousand empty seats at Twickenham is no accident and neither was this outcome.",
        reply: null,
        is_applicable: false,
        has_doc: false,
        is_complete: false,
        is_flagged: false,
        is_required: true,
        status: null,
        children: [
          {
            id: 27,
            parent_id: 25,
            sequence: 2,
            query:
              "When he decided on a career switch into politics, he wasn’t required, as many wannabe parliamentarians are, to demonstrate his commitment by first fighting an unwinnable constituency. He bagged a safe Conservative seat at the first time of asking. He was an MP at the age of 34 and chancellor before he turned 40. And then the wheel of fortune turned against him. He was promoted to Number 10 at the worst point of the political cycle to become prime minister.",
            reply: null,
            is_applicable: false,
            has_doc: false,
            is_complete: false,
            is_flagged: false,
            is_required: false,
            status: null,
            children: [],
            siblings: [2],
            level: 5,
            sequence_in_levels: [1, 3, 1, 1, 2],
          },
        ],
        siblings: [1],
        level: 4,
        sequence_in_levels: [1, 3, 1, 1],
      },
    ],
    siblings: [1, 2],
    level: 3,
    sequence_in_levels: [1, 3, 1],
  },
  {
    id: 25,
    parent_id: 24,
    sequence: 1,
    query:
      "The list of famous English sporting defeats has a new entry. Congratulations to the great rugby nation of Fiji for rewriting Pacific Island oval ball history but never before has English rugby taken such a massive reputational dive. To say Steve Borthwick’s team have a few problems to solve before the Rugby World Cup kicks off next month is the understatement of the decade.\n\nShort of winning Olympic Sevens gold for the first time in Rio in 2016 it is difficult to imagine a result that will generate more pride and joy in the streets of Suva and Lautoka and every rugby-mad village in between. Equally, the frustrated gnashing of teeth in Middle England is now deafening. Twenty-five thousand empty seats at Twickenham is no accident and neither was this outcome.",
    reply: null,
    is_applicable: false,
    has_doc: false,
    is_complete: false,
    is_flagged: false,
    is_required: true,
    status: null,
    children: [
      {
        id: 27,
        parent_id: 25,
        sequence: 2,
        query:
          "When he decided on a career switch into politics, he wasn’t required, as many wannabe parliamentarians are, to demonstrate his commitment by first fighting an unwinnable constituency. He bagged a safe Conservative seat at the first time of asking. He was an MP at the age of 34 and chancellor before he turned 40. And then the wheel of fortune turned against him. He was promoted to Number 10 at the worst point of the political cycle to become prime minister.",
        reply: null,
        is_applicable: false,
        has_doc: false,
        is_complete: false,
        is_flagged: false,
        is_required: false,
        status: null,
        children: [],
        siblings: [2],
        level: 5,
        sequence_in_levels: [1, 3, 1, 1, 2],
      },
    ],
    siblings: [1],
    level: 4,
    sequence_in_levels: [1, 3, 1, 1],
  },
  {
    id: 27,
    parent_id: 25,
    sequence: 2,
    query:
      "When he decided on a career switch into politics, he wasn’t required, as many wannabe parliamentarians are, to demonstrate his commitment by first fighting an unwinnable constituency. He bagged a safe Conservative seat at the first time of asking. He was an MP at the age of 34 and chancellor before he turned 40. And then the wheel of fortune turned against him. He was promoted to Number 10 at the worst point of the political cycle to become prime minister.",
    reply: null,
    is_applicable: false,
    has_doc: false,
    is_complete: false,
    is_flagged: false,
    is_required: false,
    status: null,
    children: [],
    siblings: [2],
    level: 5,
    sequence_in_levels: [1, 3, 1, 1, 2],
  },
  {
    id: 23,
    parent_id: 19,
    sequence: 2,
    query: "there must be some contents",
    reply: null,
    is_applicable: false,
    has_doc: false,
    is_complete: false,
    is_flagged: false,
    is_required: false,
    status: null,
    children: [],
    siblings: [1, 2],
    level: 3,
    sequence_in_levels: [1, 3, 2],
  },
  {
    id: 21,
    parent_id: 18,
    sequence: 4,
    query:
      "Furnish a copy of a valid Building Energy Rating certificate and related advisory report in respect of the property.",
    reply: null,
    is_applicable: true,
    has_doc: true,
    is_complete: true,
    is_flagged: true,
    is_required: true,
    status: null,
    children: [],
    siblings: [4, 3, 2, 1],
    level: 2,
    sequence_in_levels: [1, 4],
  },
]
